version: '3'

services:

  mongodb:
    image: mongo:5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    networks:
      - private
    volumes:
      - database:/data/db

  api:
    build:
      context: ./
      dockerfile: ./docker/api/Dockerfile
    restart: always
    environment:
#      MONGODB_URL: mongodb-srv://root:example@mongodb:27017/mappings?retryWrites=true&w=majority
      MONGODB_URL: mongodb://root:password@mongodb:27017/
    ports:
      - "80:80"
    networks:
      - private
      - public
    depends_on:
      - mongodb

#  proxy:
#    build: ./docker/nginx
#    restart: always
#    ports:
#      - "80:80"
#    networks:
#      - public
#    depends_on:
#      - api

#  redis:
#    image: redis:7
#    networks:
#      - cache

networks:
  public:
  private:

volumes:
  database:
